### ISSUE TITLE
[Backend Environment] Setup CI with Github Actions

### ISSUE THREAD

**Issue by skosman** [seng499-company2/back-end#15]
**Description:**
Setup continuous integration using Github actions so that our system to ensure that new code does not produce unintended defects. 

**Reference:** 
Django and PostgreSQL
- https://www.hacksoft.io/blog/github-actions-in-action-setting-up-django-and-postgres
- https://www.codingforentrepreneurs.com/blog/django-github-actions

**Comment by kunnapool** [comment]
Implemented in #22
